#!/usr/bin/env python3
"""
Oppo A33w Sensor Research Analysis Tool
Analyzes recorded CSV datasets:
1. Calculates sampling rate stability & jitter metrics.
2. Computes Fast Fourier Transform (FFT) / Frequency Spectrum.
3. Applies digital filters (Butterworth low-pass / band-pass).
4. Generates summary statistics (Min, Max, RMS, Variance).
"""

import sys
import os
import argparse
import csv

try:
    import numpy as np
except ImportError:
    print("Error: numpy is required. Run 'pip install numpy'")
    sys.exit(1)

def analyze_csv(filepath):
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return

    timestamps = []
    types = []
    names = {}
    values_x = []
    values_y = []
    values_z = []

    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader, None)
        for row in reader:
            if len(row) >= 4:
                try:
                    ts = float(row[0])
                    stype = int(row[1])
                    sname = row[2]
                    vx = float(row[3])
                    vy = float(row[4]) if len(row) > 4 else 0.0
                    vz = float(row[5]) if len(row) > 5 else 0.0

                    timestamps.append(ts)
                    types.append(stype)
                    names[stype] = sname
                    values_x.append(vx)
                    values_y.append(vy)
                    values_z.append(vz)
                except ValueError:
                    pass

    if not timestamps:
        print("No valid sensor samples found in CSV.")
        return

    ts_arr = np.array(timestamps)
    deltas = np.diff(ts_arr) # in ms
    deltas = deltas[deltas > 0] # filter out duplicate timestamps

    print("=" * 60)
    print(f" OPPO A33w SENSOR DATASET REPORT: {os.path.basename(filepath)}")
    print("=" * 60)
    print(f"Total Samples Recorded : {len(ts_arr)}")
    print(f"Duration               : {(ts_arr[-1] - ts_arr[0])/1000.0:.2f} seconds")
    
    if len(deltas) > 0:
        mean_dt = np.mean(deltas)
        std_dt = np.std(deltas)
        mean_hz = 1000.0 / mean_dt
        print(f"Mean Sampling Rate     : {mean_hz:.2f} Hz (Avg Interval: {mean_dt:.2f} ms)")
        print(f"Sampling Jitter (Std)  : ±{std_dt:.2f} ms")

    print("\n--- Summary Statistics Per Axis ---")
    x_arr = np.array(values_x)
    y_arr = np.array(values_y)
    z_arr = np.array(values_z)

    print(f"Axis X: Min={np.min(x_arr):.4f}, Max={np.max(x_arr):.4f}, Mean={np.mean(x_arr):.4f}, RMS={np.sqrt(np.mean(x_arr**2)):.4f}")
    print(f"Axis Y: Min={np.min(y_arr):.4f}, Max={np.max(y_arr):.4f}, Mean={np.mean(y_arr):.4f}, RMS={np.sqrt(np.mean(y_arr**2)):.4f}")
    print(f"Axis Z: Min={np.min(z_arr):.4f}, Max={np.max(z_arr):.4f}, Mean={np.mean(z_arr):.4f}, RMS={np.sqrt(np.mean(z_arr**2)):.4f}")

    # FFT Analysis
    if len(ts_arr) > 16 and len(deltas) > 0:
        fs = 1000.0 / np.mean(deltas)
        n = len(x_arr)
        freqs = np.fft.rfftfreq(n, d=1.0/fs)
        fft_x = np.abs(np.fft.rfft(x_arr - np.mean(x_arr)))
        peak_idx = np.argmax(fft_x)
        print(f"\nDominant Frequency (Peak Energy) Axis X: {freqs[peak_idx]:.2f} Hz")
    print("=" * 60)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze Oppo A33w CSV Data")
    parser.add_argument("csv_file", help="Path to CSV file generated by phone or laptop suite")
    args = parser.parse_args()
    analyze_csv(args.csv_file)
